import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const TODAY = new Date().toLocaleDateString("en-US", {
  year: "numeric",
  month: "long",
  day: "numeric",
});

const Terms = () => {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <main className="flex-1 pt-24 pb-16">
        <div className="container max-w-3xl mx-auto px-4 sm:px-6">
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-4 text-foreground">
            Terms of Service
          </h1>
          <p className="text-muted-foreground mb-1">Effective Date: {TODAY}</p>
          <p className="text-muted-foreground mb-10">Last Updated: {TODAY}</p>

          <div className="space-y-6 text-foreground/90 leading-relaxed">
            <p>
              These Terms of Service ("Terms") govern your use of Mayday AI's services and the maydayautomation.com website. By using our services or website, you agree to these Terms.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Services</h2>
            <p>
              Mayday AI ("we," "us," or "our") builds and operates AI-powered personal assistants and automation workflows for small businesses. Specific services, deliverables, and pricing are defined in separate service agreements between Mayday AI and each client.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">SMS Communications</h2>
            <p>If you opt in to receive text messages from Mayday AI:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>You authorize Mayday AI to send you text messages in connection with the AI assistant service you have engaged.</li>
              <li>Messages may include reminders, notes, confirmations, and operational notifications generated by your AI assistant.</li>
              <li>Message frequency varies based on your service usage.</li>
              <li>Message and data rates may apply, depending on your mobile carrier and plan.</li>
              <li>Consent to receive these messages is not a condition of engaging any Mayday AI service.</li>
              <li>You may opt out at any time by replying STOP to any message we send. Reply HELP for assistance.</li>
              <li>Mayday AI is not responsible for the cost of receiving messages or for messages that fail to deliver due to your carrier, device, or network conditions.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use our services for any unlawful purpose</li>
              <li>Attempt to reverse engineer, decompile, or interfere with our systems</li>
              <li>Impersonate any person or entity</li>
              <li>Use our services to send spam, unsolicited communications, or harassing content</li>
              <li>Resell or redistribute our services without prior written agreement</li>
            </ul>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Intellectual Property</h2>
            <p>
              The maydayautomation.com website, including text, graphics, code, and design, is owned by Mayday AI and protected by copyright and other intellectual property laws. You may not copy, modify, or distribute our content without prior written permission.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Third Party Services</h2>
            <p>
              Our services rely on third-party providers including Twilio (telecommunications), Anthropic and OpenAI (AI models), and other infrastructure providers. We are not responsible for outages, errors, or content originating from third-party services.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Disclaimers</h2>
            <p>
              Our services are provided "as is" and "as available" without warranties of any kind, express or implied. Mayday AI does not warrant that services will be uninterrupted, error-free, or secure. AI-generated content may contain inaccuracies; you are responsible for reviewing output before acting on it.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Mayday AI's total liability for any claim arising out of or related to these Terms or our services is limited to the amount you paid Mayday AI in the twelve months preceding the claim. Mayday AI is not liable for indirect, incidental, consequential, or punitive damages.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Mayday AI from claims, damages, and expenses arising out of your misuse of our services or violation of these Terms.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Termination</h2>
            <p>
              We may suspend or terminate access to our services at any time, with or without notice, for any violation of these Terms or for any other reason. You may stop using our services at any time.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of North Carolina, without regard to conflict of law principles. Any dispute arising under these Terms will be resolved in the state or federal courts located in North Carolina.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Changes to These Terms</h2>
            <p>
              We may revise these Terms from time to time. The "Last Updated" date reflects the most recent revision. Continued use of our services after changes constitutes acceptance of the revised Terms.
            </p>

            <h2 className="text-2xl font-semibold text-foreground pt-4">Contact</h2>
            <p>
              Mayday AI<br />
              Cary, North Carolina<br />
              Email: masondavisai@gmail.com<br />
              Phone: 919-244-3451
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
